(function initCatalog(root, factory) {
  const catalog = factory();
  if (typeof module === 'object' && module.exports) {
    module.exports = catalog;
  }
  if (root) {
    root.CodePickerCatalog = catalog;
  }
})(typeof globalThis !== 'undefined' ? globalThis : this, function createCatalog() {
  'use strict';

  return {
    name: 'Project Controls Code Picker — demo catalog v0.1',
    version: 'demo-v0.1',
    isDemo: true,
    notice: 'Illustrative codes only. Import the approved Project Controls / Finance dictionary before live use.',
    entries: [
      {
        code: 'DEMO-0010',
        name: 'Development and site due diligence',
        description: 'Early site, utility, environmental, entitlement, and feasibility professional services.',
        fund: ['base-capital'],
        phase: ['0-strategy'],
        discipline: ['development'],
        costType: ['professional-services'],
        keywords: ['site selection', 'survey', 'geotechnical', 'environmental', 'feasibility', 'utility study'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-0020',
        name: 'Entitlements, permits, and agency fees',
        description: 'Government applications, permits, reviews, and jurisdictional fees tied to project development.',
        fund: ['base-capital'],
        phase: ['0-strategy', '1-concept', '2-design'],
        discipline: ['development'],
        costType: ['permits-fees'],
        keywords: ['permit', 'plan review', 'entitlement', 'zoning', 'impact fee', 'agency'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-0030',
        name: 'Architecture and engineering design',
        description: 'Design professional services from concept through issued construction documents.',
        fund: ['base-capital'],
        phase: ['1-concept', '2-design'],
        discipline: ['design-engineering'],
        costType: ['professional-services'],
        keywords: ['architect', 'engineer', 'drawings', 'specifications', 'basis of design', 'BIM', 'design assist'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-0040',
        name: 'Preconstruction and estimating services',
        description: 'Estimating, constructability, logistics planning, scheduling, and preconstruction support.',
        fund: ['base-capital'],
        phase: ['1-concept', '2-design'],
        discipline: ['project-controls'],
        costType: ['professional-services'],
        keywords: ['estimate', 'preconstruction', 'constructability', 'bid package', 'baseline schedule', 'logistics'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-0100',
        name: 'Project management and project controls',
        description: 'Project management, cost control, scheduling, change control, reporting, and document control services.',
        fund: ['base-capital'],
        phase: ['all'],
        discipline: ['project-controls'],
        costType: ['professional-services'],
        keywords: ['project management', 'scheduler', 'cost engineer', 'controls', 'reporting', 'document control'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-0110',
        name: 'General conditions and temporary facilities',
        description: 'Project-wide supervision, offices, temporary facilities, logistics, and common-use support.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation', '5-commissioning'],
        discipline: ['general-conditions'],
        costType: ['temporary-works'],
        keywords: ['job trailer', 'temporary fence', 'supervision', 'site logistics', 'temporary facility', 'general conditions'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-1000',
        name: 'Civil and sitework subcontract',
        description: 'Earthwork, grading, roads, drainage, underground utilities, and related site installation.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation'],
        discipline: ['civil-site'],
        costType: ['subcontract'],
        keywords: ['earthwork', 'excavation', 'grading', 'stormwater', 'road', 'ductbank', 'underground', 'sitework'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-1010',
        name: 'Civil and site materials',
        description: 'Direct-purchase civil, drainage, paving, and underground utility materials.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation'],
        discipline: ['civil-site'],
        costType: ['material'],
        keywords: ['aggregate', 'pipe', 'manhole', 'asphalt', 'curb', 'drainage material'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-1020',
        name: 'Utility interconnection and service fees',
        description: 'Utility studies, interconnection, service, contribution-in-aid, and related external-provider fees.',
        fund: ['base-capital'],
        phase: ['0-strategy', '1-concept', '2-design', '3-procurement'],
        discipline: ['utilities'],
        costType: ['permits-fees'],
        keywords: ['utility', 'interconnection', 'service fee', 'load study', 'substation', 'power provider'],
        active: true,
        requiresReview: true,
        reviewNote: 'Confirm contract ownership and whether the fee belongs to the project, utility, or customer.',
      },
      {
        code: 'DEMO-2000',
        name: 'Concrete and structural subcontract',
        description: 'Foundations, slabs, equipment pads, structural steel, and primary structural installation.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation'],
        discipline: ['structural'],
        costType: ['subcontract'],
        keywords: ['concrete', 'foundation', 'slab', 'steel', 'equipment pad', 'embed', 'structure'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-2100',
        name: 'Building enclosure and roofing subcontract',
        description: 'Exterior walls, roofing, waterproofing, doors, and weather-tight enclosure work.',
        fund: ['base-capital'],
        phase: ['4-installation'],
        discipline: ['building-envelope'],
        costType: ['subcontract'],
        keywords: ['roof', 'wall panel', 'waterproofing', 'door', 'weather tight', 'enclosure'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-3000',
        name: 'Electrical equipment purchase',
        description: 'Direct or owner-furnished purchase of major electrical distribution and backup-power equipment.',
        fund: ['owner-furnished'],
        phase: ['3-procurement'],
        discipline: ['electrical'],
        costType: ['equipment'],
        keywords: ['generator', 'genset', 'switchgear', 'transformer', 'UPS', 'PDU', 'busway', 'battery', 'electrical equipment'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-3010',
        name: 'Electrical installation subcontract',
        description: 'Field installation of electrical distribution, grounding, raceway, conductors, and equipment connections.',
        fund: ['base-capital'],
        phase: ['4-installation'],
        discipline: ['electrical'],
        costType: ['subcontract'],
        keywords: ['electrician', 'cable', 'conduit', 'grounding', 'termination', 'electrical install', 'raceway'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-3020',
        name: 'Electrical installation materials',
        description: 'Direct-purchase raceway, conductors, supports, grounding, and electrical installation materials.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation'],
        discipline: ['electrical'],
        costType: ['material'],
        keywords: ['copper', 'cable', 'conduit', 'tray', 'grounding material', 'electrical material'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-3030',
        name: 'Temporary construction power',
        description: 'Temporary power equipment, distribution, metering, fuel, and installation used during construction.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation'],
        discipline: ['electrical'],
        costType: ['temporary-works'],
        keywords: ['temporary power', 'temp power', 'construction power', 'rental generator', 'meter'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-4000',
        name: 'Mechanical equipment purchase',
        description: 'Direct or owner-furnished purchase of major cooling, pumping, heat-rejection, and air-handling equipment.',
        fund: ['owner-furnished'],
        phase: ['3-procurement'],
        discipline: ['mechanical'],
        costType: ['equipment'],
        keywords: ['chiller', 'cooling tower', 'pump', 'CRAH', 'CRAC', 'air handler', 'heat exchanger', 'mechanical equipment'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-4010',
        name: 'Mechanical installation subcontract',
        description: 'Field installation of cooling systems, hydronic piping, plumbing, insulation, and mechanical equipment connections.',
        fund: ['base-capital'],
        phase: ['4-installation'],
        discipline: ['mechanical'],
        costType: ['subcontract'],
        keywords: ['mechanical contractor', 'piping', 'plumbing', 'insulation', 'HVAC install', 'hydronic'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-4020',
        name: 'Mechanical installation materials',
        description: 'Direct-purchase pipe, valves, fittings, supports, insulation, and mechanical installation materials.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation'],
        discipline: ['mechanical'],
        costType: ['material'],
        keywords: ['pipe', 'valve', 'fitting', 'support', 'insulation', 'mechanical material'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-4100',
        name: 'Generator fuel system',
        description: 'Fuel storage, transfer, piping, monitoring, and related generator fuel-system equipment and installation.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation'],
        discipline: ['mechanical'],
        costType: ['equipment', 'subcontract'],
        keywords: ['fuel tank', 'day tank', 'fuel polishing', 'diesel', 'fuel piping', 'generator fuel'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-5000',
        name: 'BMS, EPMS, and controls integration',
        description: 'Building and electrical power monitoring controls, panels, networks, programming, and systems integration.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation', '5-commissioning'],
        discipline: ['controls'],
        costType: ['subcontract'],
        keywords: ['BMS', 'EPMS', 'controls', 'programming', 'point list', 'sequence', 'integration', 'SCADA'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-5100',
        name: 'Fire and life-safety systems',
        description: 'Fire suppression, detection, alarm, monitoring, and acceptance-testing scope.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation', '5-commissioning'],
        discipline: ['fire-life-safety'],
        costType: ['subcontract'],
        keywords: ['fire alarm', 'sprinkler', 'suppression', 'detection', 'life safety', 'acceptance test'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-5200',
        name: 'Low-voltage, telecom, and security systems',
        description: 'Structured cabling, pathways, access control, CCTV, telecom, and related low-voltage systems.',
        fund: ['base-capital'],
        phase: ['3-procurement', '4-installation', '5-commissioning'],
        discipline: ['low-voltage-security'],
        costType: ['subcontract'],
        keywords: ['low voltage', 'telecom', 'fiber', 'structured cabling', 'access control', 'CCTV', 'security'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-6000',
        name: 'Commissioning authority services',
        description: 'Independent commissioning planning, design review, issue management, testing, and turnover support.',
        fund: ['base-capital'],
        phase: ['1-concept', '2-design', '3-procurement', '4-installation', '5-commissioning', '6-turnover'],
        discipline: ['commissioning'],
        costType: ['professional-services'],
        keywords: ['commissioning authority', 'CxA', 'commissioning plan', 'functional test', 'IST', 'issue log'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-6010',
        name: 'OEM startup and field service',
        description: 'Manufacturer startup, field engineering, warranty activation, and test support for major equipment.',
        fund: ['owner-furnished'],
        phase: ['5-commissioning'],
        discipline: ['commissioning'],
        costType: ['professional-services'],
        keywords: ['startup', 'field service', 'OEM', 'vendor technician', 'warranty activation', 'SAT'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-6100',
        name: 'Testing, balancing, and special inspections',
        description: 'TAB, third-party testing, special inspections, and independent quality-verification services.',
        fund: ['base-capital'],
        phase: ['4-installation', '5-commissioning'],
        discipline: ['quality-testing'],
        costType: ['professional-services'],
        keywords: ['TAB', 'testing', 'balancing', 'special inspection', 'NDT', 'third party', 'quality'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-7000',
        name: 'Turnover and closeout documentation',
        description: 'As-builts, O&M manuals, asset data, training records, warranties, and closeout support.',
        fund: ['base-capital'],
        phase: ['5-commissioning', '6-turnover'],
        discipline: ['turnover-closeout'],
        costType: ['professional-services'],
        keywords: ['closeout', 'turnover', 'as-built', 'O&M manual', 'asset data', 'training', 'warranty'],
        active: true,
        requiresReview: false,
        reviewNote: '',
      },
      {
        code: 'DEMO-8000',
        name: 'Base project contingency',
        description: 'Unallocated base-project contingency controlled under the approved contingency policy.',
        fund: ['contingency'],
        phase: ['all'],
        discipline: ['all'],
        costType: ['contingency'],
        keywords: ['contingency', 'unallocated', 'management reserve', 'unknown scope'],
        active: true,
        requiresReview: true,
        reviewNote: 'Do not post directly without the project’s documented contingency authorization and transfer process.',
      },
      {
        code: 'DEMO-8100',
        name: 'Approved change budget',
        description: 'Budget established for a formally approved project change event.',
        fund: ['approved-change'],
        phase: ['all'],
        discipline: ['all'],
        costType: ['other'],
        keywords: ['change order', 'approved change', 'budget transfer', 'PCO', 'change event'],
        active: true,
        requiresReview: true,
        reviewNote: 'Enter the approved change-event reference and confirm budget incorporation before posting.',
      },
      {
        code: 'DEMO-8200',
        name: 'Approved allowance drawdown',
        description: 'Funds released from an approved allowance for defined project scope.',
        fund: ['allowance'],
        phase: ['all'],
        discipline: ['all'],
        costType: ['other'],
        keywords: ['allowance', 'drawdown', 'budget release', 'allowance log'],
        active: true,
        requiresReview: true,
        reviewNote: 'Confirm the allowance source, remaining balance, and required approval before posting.',
      },
      {
        code: 'DEMO-8300',
        name: 'Reimbursable owner or customer work',
        description: 'Separately tracked work expected to be reimbursed under an approved agreement.',
        fund: ['reimbursable'],
        phase: ['all'],
        discipline: ['all'],
        costType: ['other'],
        keywords: ['reimbursable', 'customer work', 'owner request', 'backcharge', 'recoverable'],
        active: true,
        requiresReview: true,
        reviewNote: 'Confirm the executed reimbursement basis, responsible party, and commercial tracking requirements.',
      },
      {
        code: 'DEMO-9000',
        name: 'Operations and maintenance expense',
        description: 'Post-turnover operational maintenance, consumables, and non-project service expense.',
        fund: ['operating-expense'],
        phase: ['6-turnover'],
        discipline: ['operations'],
        costType: ['professional-services', 'material'],
        keywords: ['maintenance', 'operations', 'consumable', 'repair', 'service contract', 'OPEX'],
        active: true,
        requiresReview: true,
        reviewNote: 'Finance must confirm operating-versus-capital treatment and the correct operating cost center.',
      },
      {
        code: 'DEMO-0999',
        name: 'Legacy mobilization placeholder',
        description: 'Retired example included only to demonstrate inactive-code handling.',
        fund: ['base-capital'],
        phase: ['3-procurement'],
        discipline: ['general-conditions'],
        costType: ['temporary-works'],
        keywords: ['legacy', 'retired', 'mobilization'],
        active: false,
        requiresReview: true,
        reviewNote: 'Retired code. Select an active replacement.',
      },
    ],
  };
});
